// src/types/config.ts
export  ConfigCategory {
  LAND_TENURE = 'LAND_TENURE',
  REVENUE_TYPE = 'REVENUE_TYPE',
  DOCUMENT_TYPE = 'DOCUMENT_TYPE',
  TRANSFER_TYPE = 'TRANSFER_TYPE',
  LAND_USE = 'LAND_USE',
  PAYMENT_METHOD = 'PAYMENT_METHOD',
  ENCUMBRANCE_TYPE = 'ENCUMBRANCE_TYPE',
  GENERAL = 'GENERAL',
  REVENUE_RATES = 'REVENUE_RATES',
}