// src/components/reports/BillsExport.tsx
import React from 'react';
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import type { BillReportItem } from '../../types/reports';

interface BillsExportProps {
  data: BillReportItem[];
  filters: Record<string, any>;
  subCities?: Array<{ sub_city_id: string; name: string }>;
  fileName?: string;
  onExportStart?: () => void;
  onExportComplete?: () => void;
  onExportError?: (error: Error) => void;
  children?: (handleExport: () => Promise<void>) => React.ReactNode;
}

export const BillsExport: React.FC<BillsExportProps> = ({
  data,
  filters,
  subCities = [],
  fileName,
  onExportStart,
  onExportComplete,
  onExportError,
  children
}) => {
  const handleExport = async () => {
    try {
      if (data.length === 0) {
        alert('No data to export');
        return;
      }

      onExportStart?.();

      const workbook = new ExcelJS.Workbook();
      workbook.creator = 'Land Management System';
      workbook.lastModifiedBy = 'System';
      workbook.created = new Date();
      workbook.modified = new Date();

      // ============== SUMMARY SHEET ==============
      await createSummarySheet(workbook, data, filters);

      // ============== BILLS DETAILS SHEET ==============
      await createBillsSheet(workbook, data);

      // ============== PAYMENT ANALYSIS SHEET ==============
      await createPaymentAnalysisSheet(workbook, data);

      // Generate filename
      const dateStr = new Date().toISOString().split('T')[0];
      const statusStr = filters.status ? `_${filters.status.toLowerCase()}` : '';
      const finalFileName = fileName || `bills_report${statusStr}_${dateStr}.xlsx`;

      // Save the file
      const buffer = await workbook.xlsx.writeBuffer();
      const blob = new Blob([buffer], { 
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' 
      });
      saveAs(blob, finalFileName);

      onExportComplete?.();
      console.log(`Exported ${data.length} bills successfully`);

    } catch (error) {
      console.error('Error exporting bills:', error);
      onExportError?.(error as Error);
      alert('Failed to export data. Please try again.');
    }
  };

  const getSubCityName = (subCityId: string): string => {
    if (!subCityId) return 'All Sub Cities';
    const subCity = subCities.find(sc => sc.sub_city_id === subCityId);
    return subCity?.name || subCityId;
  };

  // Format for regular numbers (counts, etc.) - no ETB
  const formatNumber = (value: number | null | undefined): string => {
    if (value === null || value === undefined) return '0';
    return value.toString();
  };

  // Format for currency values - with ETB
  const formatCurrency = (value: number | null | undefined): string => {
    if (value === null || value === undefined) return '0.00';
    // Ensure we're working with a number
    const numValue = typeof value === 'string' ? parseFloat(value) : value;
    return `${numValue.toFixed(2)} ETB`;
  };

  // Safe number conversion for calculations
  const toNumber = (value: any): number => {
    if (value === null || value === undefined) return 0;
    if (typeof value === 'number') return value;
    if (typeof value === 'string') {
      const parsed = parseFloat(value);
      return isNaN(parsed) ? 0 : parsed;
    }
    return 0;
  };

  const createSummarySheet = async (
    workbook: ExcelJS.Workbook, 
    data: BillReportItem[],
    filters: Record<string, any>,
  ) => {
    const summarySheet = workbook.addWorksheet('Summary', {
      properties: { defaultColWidth: 25 }
    });

    // Title
    summarySheet.mergeCells('A1:D1');
    const titleRow = summarySheet.getRow(1);
    titleRow.getCell(1).value = 'Bills Report Summary';
    titleRow.getCell(1).font = { size: 18, bold: true, color: { argb: '2F5597' } };
    titleRow.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };
    titleRow.height = 30;

    // Report Info Section
    summarySheet.addRow([]);
    summarySheet.addRow(['Report Information:']);
    summarySheet.getRow(3).getCell(1).font = { bold: true, size: 12 };

    // Convert all amount_due to numbers for calculations
    const totalAmount = data.reduce((sum, item) => sum + toNumber(item.amount_due), 0);
    const totalPaid = data.filter(item => item.payment_status === 'PAID').length;
    const totalUnpaid = data.filter(item => item.payment_status === 'UNPAID').length;
    const totalOverdue = data.filter(item => item.payment_status === 'OVERDUE').length;
    const totalPartial = data.filter(item => item.payment_status === 'PARTIAL').length;

    const infoRows = [
      ['Generated Date:', new Date().toLocaleString()],
      ['Generated By:', 'System'],
      ['Total Bills:', formatNumber(data.length)], // Just number, no ETB
      ['Sub City:', getSubCityName(filters.subcityId)],
      ['Status Filter:', filters.status || 'All Statuses'],
      ['Date Range:', filters.fromDate && filters.toDate 
        ? `${new Date(filters.fromDate).toLocaleDateString()} to ${new Date(filters.toDate).toLocaleDateString()}`
        : 'All Dates'],
      ['Total Amount Due:', formatCurrency(totalAmount)], // Currency with ETB
      ['Average Amount:', formatCurrency(totalAmount / data.length)], // Currency with ETB
      ['Paid Bills:', `${formatNumber(totalPaid)} (${((totalPaid / data.length) * 100).toFixed(2)}%)`],
      ['Unpaid Bills:', `${formatNumber(totalUnpaid)} (${((totalUnpaid / data.length) * 100).toFixed(2)}%)`],
      ['Overdue Bills:', `${formatNumber(totalOverdue)} (${((totalOverdue / data.length) * 100).toFixed(2)}%)`],
      ['Partial Bills:', `${formatNumber(totalPartial)} (${((totalPartial / data.length) * 100).toFixed(2)}%)`]
    ];

    infoRows.forEach((row) => {
      const addedRow = summarySheet.addRow(row);
      addedRow.getCell(1).font = { bold: true };
      addedRow.height = 20;
    });

    // Style the sheet
    summarySheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });
  };

  const createBillsSheet = async (workbook: ExcelJS.Workbook, data: BillReportItem[]) => {
    const billsSheet = workbook.addWorksheet('Bills Details', {
      properties: { defaultColWidth: 15 },
      views: [{
        state: 'frozen',
        ySplit: 1,
        xSplit: 0
      }]
    });

    // Define columns
    billsSheet.columns = [
      { header: 'UPIN', key: 'upin', width: 20 },
      { header: 'Installment #', key: 'installmentNumber', width: 15 },
      { header: 'Fiscal Year', key: 'fiscalYear', width: 15 },
      { header: 'Owner Name', key: 'ownerName', width: 30 },
      { header: 'Phone Number', key: 'phone', width: 18 },
      { header: 'Sub City', key: 'subCity', width: 18 },
      { header: 'Base Payment', key: 'basePayment', width: 18 },
      { header: 'Amount Due', key: 'amountDue', width: 18 },
      { header: 'Due Date', key: 'dueDate', width: 15 },
      { header: 'Status', key: 'status', width: 12 },
      { header: 'Interest', key: 'interest', width: 15 },
      { header: 'Penalty', key: 'penalty', width: 15 }
    ];

    // Style header
    const headerRow = billsSheet.getRow(1);
    headerRow.height = 30;
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, size: 12, color: { argb: 'FFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: '2F5597' }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // Add data rows
    data.forEach((item) => {
      // Convert all numeric values to numbers
      const basePayment = toNumber(item.base_payment);
      const amountDue = toNumber(item.amount_due);
      const interestAmount = item.interest_amount ? toNumber(item.interest_amount) : null;
      const penaltyAmount = item.penalty_amount ? toNumber(item.penalty_amount) : null;

      const row = billsSheet.addRow({
        upin: item.upin,
        installmentNumber: item.installment_number,
        fiscalYear: item.fiscal_year || '-',
        ownerName: item.full_name,
        phone: item.phone_number || '-',
        subCity: item.subcity_name,
        basePayment: formatCurrency(basePayment),
        amountDue: formatCurrency(amountDue),
        dueDate: new Date(item.due_date).toLocaleDateString(),
        status: item.payment_status,
        interest: interestAmount ? formatCurrency(interestAmount) : '-',
        penalty: penaltyAmount ? formatCurrency(penaltyAmount) : '-'
      });

      // Style based on status
      const statusCell = row.getCell('status');
      const statusColors: Record<string, { bg: string, text: string }> = {
        PAID: { bg: 'C6EFCE', text: '006100' },
        UNPAID: { bg: 'FFEB9C', text: '9C6500' },
        OVERDUE: { bg: 'FFC7CE', text: '9C0006' },
        PARTIAL: { bg: 'D9E1F2', text: '2F5597' }
      };

      const color = statusColors[item.payment_status];
      if (color) {
        statusCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: color.bg }
        };
        statusCell.font = { color: { argb: color.text } };
      }

      // Highlight overdue amounts
      if (item.payment_status === 'OVERDUE') {
        row.getCell('amountDue').font = { bold: true, color: { argb: '9C0006' } };
      }

      // Set number formats for numeric columns
      row.getCell('basePayment').numFmt = '#,##0.00 "ETB"';
      row.getCell('amountDue').numFmt = '#,##0.00 "ETB"';
      if (interestAmount) {
        row.getCell('interest').numFmt = '#,##0.00 "ETB"';
      }
      if (penaltyAmount) {
        row.getCell('penalty').numFmt = '#,##0.00 "ETB"';
      }

      // Add borders
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
        cell.alignment = { vertical: 'middle', wrapText: true };
      });

      // Alternate row colors
      if (row.number % 2 === 0) {
        row.eachCell((cell) => {
          if (!cell.fill ) {
            cell.fill = {
              type: 'pattern',
              pattern: 'solid',
              fgColor: { argb: 'F2F2F2' }
            };
          }
        });
      }
    });

    // Add auto-filter
    billsSheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: billsSheet.columns.length }
    };
  };

  const createPaymentAnalysisSheet = async (workbook: ExcelJS.Workbook, data: BillReportItem[]) => {
    const analysisSheet = workbook.addWorksheet('Payment Analysis', {
      properties: { defaultColWidth: 20 }
    });

    // Title
    analysisSheet.mergeCells('A1:C1');
    const titleRow = analysisSheet.getRow(1);
    titleRow.getCell(1).value = 'Payment Analysis';
    titleRow.getCell(1).font = { size: 16, bold: true, color: { argb: '2F5597' } };
    titleRow.getCell(1).alignment = { horizontal: 'center' };
    titleRow.height = 25;

    // Monthly Breakdown
    analysisSheet.addRow([]);
    analysisSheet.addRow(['Monthly Breakdown:']);
    analysisSheet.getRow(3).getCell(1).font = { bold: true };

    const monthlyData = new Map<string, { count: number, total: number, paid: number }>();
    
    data.forEach(item => {
      const month = new Date(item.due_date).toLocaleString('default', { month: 'long', year: 'numeric' });
      const current = monthlyData.get(month) || { count: 0, total: 0, paid: 0 };
      
      current.count++;
      current.total += toNumber(item.amount_due);
      if (item.payment_status === 'PAID') {
        current.paid += toNumber(item.amount_due);
      }
      
      monthlyData.set(month, current);
    });

    analysisSheet.addRow(['Month', 'Bills Count', 'Total Due', 'Paid Amount', 'Collection Rate']);
    monthlyData.forEach((value, month) => {
      const collectionRate = value.total > 0 ? (value.paid / value.total) * 100 : 0;
      analysisSheet.addRow([
        month,
        formatNumber(value.count), // Just number, no ETB
        formatCurrency(value.total),
        formatCurrency(value.paid),
        `${collectionRate.toFixed(2)}%`
      ]);
    });

    // Overdue Summary
    analysisSheet.addRow([]);
    analysisSheet.addRow(['Overdue Summary:']);
    analysisSheet.getRow(3 + monthlyData.size + 3).getCell(1).font = { bold: true };

    const overdueBills = data.filter(item => item.payment_status === 'OVERDUE');
    const totalOverdue = overdueBills.reduce((sum, item) => sum + toNumber(item.amount_due), 0);

    analysisSheet.addRow(['Total Overdue Bills:', formatNumber(overdueBills.length)]); // Just number
    analysisSheet.addRow(['Total Overdue Amount:', formatCurrency(totalOverdue)]); // Currency with ETB
    analysisSheet.addRow(['Average Overdue Amount:', overdueBills.length > 0 
      ? formatCurrency(totalOverdue / overdueBills.length)
      : '0.00 ETB']);

    // Payment Status Distribution
    analysisSheet.addRow([]);
    analysisSheet.addRow(['Payment Status Distribution:']);
    analysisSheet.getRow(3 + monthlyData.size + overdueBills.length + 10).getCell(1).font = { bold: true };

    const statusCounts = {
      PAID: data.filter(item => item.payment_status === 'PAID').length,
      UNPAID: data.filter(item => item.payment_status === 'UNPAID').length,
      OVERDUE: data.filter(item => item.payment_status === 'OVERDUE').length,
      PARTIAL: data.filter(item => item.payment_status === 'PARTIAL').length
    };

    const statusAmounts = {
      PAID: data.filter(item => item.payment_status === 'PAID').reduce((sum, item) => sum + toNumber(item.amount_due), 0),
      UNPAID: data.filter(item => item.payment_status === 'UNPAID').reduce((sum, item) => sum + toNumber(item.amount_due), 0),
      OVERDUE: data.filter(item => item.payment_status === 'OVERDUE').reduce((sum, item) => sum + toNumber(item.amount_due), 0),
      PARTIAL: data.filter(item => item.payment_status === 'PARTIAL').reduce((sum, item) => sum + toNumber(item.amount_due), 0)
    };

    analysisSheet.addRow(['Status', 'Count', 'Percentage', 'Total Amount']);
    Object.entries(statusCounts).forEach(([status, count]) => {
      if (count > 0) {
        analysisSheet.addRow([
          status,
          formatNumber(count), // Just number
          `${((count / data.length) * 100).toFixed(2)}%`,
          formatCurrency(statusAmounts[status as keyof typeof statusAmounts]) // Currency with ETB
        ]);
      }
    });

    // Style the analysis sheet
    analysisSheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
        
        // Set number format for amount columns
        if (typeof cell.value === 'number' || (cell.value && cell.value.toString().includes('ETB'))) {
          cell.numFmt = '#,##0.00 "ETB"';
        }
      });
    });
  };

  // Render prop pattern
  if (children) {
    return <>{children(handleExport)}</>;
  }

  // Default render as a button
  return (
    <button
      onClick={handleExport}
      disabled={data.length === 0}
      className="px-4 py-2 text-sm font-medium text-white bg-green-600 rounded-lg hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed"
    >
      Export to Excel
    </button>
  );
};