// components/reports/EncumbrancesExport.tsx
import React from 'react';
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import type { EncumbranceReportItem } from '../../types/reports';

interface EncumbrancesExportProps {
  data: EncumbranceReportItem[];
  filters: Record<string, any>;
  fileName?: string;
  onExportStart?: () => void;
  onExportComplete?: () => void;
  onExportError?: (error: Error) => void;
  children?: (handleExport: () => Promise<void>) => React.ReactNode;
}

export const EncumbrancesExport: React.FC<EncumbrancesExportProps> = ({
  data,
  filters,
  fileName,
  onExportStart,
  onExportComplete,
  onExportError,
  children
}) => {
  const handleExport = async () => {
    try {
      if (data.length === 0) {
        alert('No data to export');
        return;
      }

      onExportStart?.();

      const workbook = new ExcelJS.Workbook();
      workbook.creator = 'Land Management System';
      workbook.lastModifiedBy = 'System';
      workbook.created = new Date();
      workbook.modified = new Date();

      // ============== SUMMARY SHEET ==============
      await createSummarySheet(workbook, data, filters);

      // ============== DETAILED REPORT SHEET ==============
      await createDetailedSheet(workbook, data);

      // ============== OWNERS SHEET ==============
      await createOwnersSheet(workbook, data);

      // Generate filename
      const dateStr = new Date().toISOString().split('T')[0];
      const filterStr = filters.subCityId ? `_${filters.subCityId}` : '';
      const finalFileName = fileName || `encumbrances_report${filterStr}_${dateStr}.xlsx`;

      // Save the file
      const buffer = await workbook.xlsx.writeBuffer();
      const blob = new Blob([buffer], { 
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' 
      });
      saveAs(blob, finalFileName);

      onExportComplete?.();
      console.log(`Exported ${data.length} parcels successfully`);

    } catch (error) {
      console.error('Error exporting encumbrances:', error);
      onExportError?.(error as Error);
      alert('Failed to export data. Please try again.');
    }
  };

  const createSummarySheet = async (
    workbook: ExcelJS.Workbook, 
    data: EncumbranceReportItem[],
    filters: Record<string, any>
  ) => {
    const summarySheet = workbook.addWorksheet('Summary', {
      properties: { defaultColWidth: 25 }
    });

    // Title
    summarySheet.mergeCells('A1:D1');
    const titleRow = summarySheet.getRow(1);
    titleRow.getCell(1).value = 'Encumbrances Report Summary';
    titleRow.getCell(1).font = { size: 18, bold: true, color: { argb: '2F5597' } };
    titleRow.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };
    titleRow.height = 30;

    // Report Info Section
    summarySheet.addRow([]);
    summarySheet.addRow(['Report Information:']);
    summarySheet.getRow(3).getCell(1).font = { bold: true, size: 12 };

    const infoRows = [
      ['Generated Date:', new Date().toLocaleString()],
      ['Generated By:', 'System'],
      ['Total Records:', data.length.toString()],
      ['Date Range:', filters.from_date && filters.to_date 
        ? `${filters.from_date} to ${filters.to_date}`
        : 'All Dates'],
      ['Sub City:', filters.subCityId || 'All Sub Cities'],
      ['Status Filter:', filters.status || 'All Statuses'],
      ['Type Filter:', filters.type || 'All Types']
    ];

    infoRows.forEach((row, index) => {
      const addedRow = summarySheet.addRow(row);
      addedRow.getCell(1).font = { bold: true };
      addedRow.height = 20;
    });

    // Statistics Section
    summarySheet.addRow([]);
    summarySheet.addRow(['Statistics:']);
    summarySheet.getRow(3 + infoRows.length + 2).getCell(1).font = { bold: true, size: 12 };

    const activeCount = data.filter(item => item.status === 'ACTIVE').length;
    const releasedCount = data.filter(item => item.status === 'RELEASED').length;

    const statsRows = [
      ['Total Parcels with Encumbrances:', data.length.toString()],
      ['Active Encumbrances:', activeCount.toString()],
      ['Released Encumbrances:', releasedCount.toString()],
      ['Active Percentage:', `${((activeCount / data.length) * 100).toFixed(2)}%`],
      ['Released Percentage:', `${((releasedCount / data.length) * 100).toFixed(2)}%`]
    ];

    statsRows.forEach(row => {
      const addedRow = summarySheet.addRow(row);
      addedRow.getCell(1).font = { bold: true };
    });

    // Style the sheet
    summarySheet.eachRow((row, rowNumber) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });
  };

  const createDetailedSheet = async (workbook: ExcelJS.Workbook, data: EncumbranceReportItem[]) => {
    const detailSheet = workbook.addWorksheet('Detailed Report', {
      properties: { defaultColWidth: 15 },
      views: [{
        state: 'frozen',
        ySplit: 1,
        xSplit: 0
      }]
    });

    // Define columns
    detailSheet.columns = [
      { header: 'UPIN', key: 'upin', width: 20 },
      { header: 'File Number', key: 'fileNumber', width: 20 },
      { header: 'Sub City', key: 'subCity', width: 15 },
      { header: 'Tabia', key: 'tabia', width: 15 },
      { header: 'Ketena', key: 'ketena', width: 15 },
      { header: 'Block', key: 'block', width: 15 },
      { header: 'Issuing Entity', key: 'issuingEntity', width: 20 },
      { header: 'Reference Number', key: 'referenceNumber', width: 20 },
      { header: 'Status', key: 'status', width: 15 },
      { header: 'Registration Date', key: 'registrationDate', width: 15 },
      { header: 'Last Updated', key: 'lastUpdated', width: 15 },
      { header: 'Owner Count', key: 'ownerCount', width: 12 }
    ];

    // Style header
    const headerRow = detailSheet.getRow(1);
    headerRow.height = 30;
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, size: 12, color: { argb: 'FFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: '2F5597' }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // Add data rows
    data.forEach((item) => {
      const row = detailSheet.addRow({
        upin: item.land_parcel.upin,
        fileNumber: item.land_parcel.file_number,
        subCity: item.land_parcel.sub_city.name,
        tabia: item.land_parcel.tabia || '-',
        ketena: item.land_parcel.ketena || '-',
        block: item.land_parcel.block || '-',
        issuingEntity: item.issuing_entity || '-',
        referenceNumber: item.reference_number || '-',
        status: item.status,
        registrationDate: new Date(item.registration_date).toLocaleDateString(),
        lastUpdated: item.updated_at ? new Date(item.updated_at).toLocaleDateString() : '-',
        ownerCount: item.land_parcel.owners?.length || 0
      });

      // Style based on status
      const statusCell = row.getCell('status');
      if (item.status === 'ACTIVE') {
        statusCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'C6EFCE' }
        };
        statusCell.font = { color: { argb: '006100' } };
      } else if (item.status === 'RELEASED') {
        statusCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFC7CE' }
        };
        statusCell.font = { color: { argb: '9C0006' } };
      }

      // Add borders
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
        cell.alignment = { vertical: 'middle', wrapText: true };
      });

      // Alternate row colors
      if (row.number % 2 === 0) {
        row.eachCell((cell) => {
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'F2F2F2' }
          };
        });
      }
    });

    // Add auto-filter
    detailSheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: detailSheet.columns.length }
    };
  };

  const createOwnersSheet = async (workbook: ExcelJS.Workbook, data: EncumbranceReportItem[]) => {
    const ownersSheet = workbook.addWorksheet('Owners Details', {
      properties: { defaultColWidth: 20 },
      views: [{
        state: 'frozen',
        ySplit: 1
      }]
    });

    ownersSheet.columns = [
      { header: 'UPIN', key: 'upin', width: 20 },
      { header: 'File Number', key: 'fileNumber', width: 20 },
      { header: 'Sub City', key: 'subCity', width: 15 },
      { header: 'Owner Name', key: 'ownerName', width: 30 },
      { header: 'Phone Number', key: 'phone', width: 20 },
   
    ];

    // Style header
    const headerRow = ownersSheet.getRow(1);
    headerRow.height = 30;
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, size: 12 };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'D9E1F2' }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center' };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // Add owner data
    let hasOwners = false;
    data.forEach((item) => {
      if (item.land_parcel.owners && item.land_parcel.owners.length > 0) {
        hasOwners = true;
        item.land_parcel.owners.forEach((ownerWrapper) => {
          const row = ownersSheet.addRow({
            upin: item.land_parcel.upin,
            fileNumber: item.land_parcel.file_number,
            subCity: item.land_parcel.sub_city.name,
            ownerName: ownerWrapper.owner.full_name,
            phone: ownerWrapper.owner.phone_number || '-',
            ownerId: ownerWrapper.owner.owner_id || '-',
            ownershipType: ownerWrapper.ownership_type || '-',
            share: ownerWrapper.share || '-'
          });

          row.eachCell((cell) => {
            cell.border = {
              top: { style: 'thin' },
              left: { style: 'thin' },
              bottom: { style: 'thin' },
              right: { style: 'thin' }
            };
            cell.alignment = { vertical: 'middle' };
          });
        });
      }
    });

    if (!hasOwners) {
      ownersSheet.addRow(['No owner data available']);
    }

    // Add auto-filter if there are rows
    if (hasOwners) {
      ownersSheet.autoFilter = {
        from: { row: 1, column: 1 },
        to: { row: 1, column: ownersSheet.columns.length }
      };
    }
  };

  // Render prop pattern
  if (children) {
    return <>{children(handleExport)}</>;
  }

  // Default render as a button
  return (
    <button
      onClick={handleExport}
      disabled={data.length === 0}
      className="px-4 py-2 text-sm font-medium text-white bg-green-600 rounded-lg hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed"
    >
      Export to Excel
    </button>
  );
};