// components/reports/LandParcelsExport.tsx
import React from 'react';
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import type { LandParcelReportItem } from '../../types/reports';

interface LandParcelsExportProps {
  data: LandParcelReportItem[];
  filters: Record<string, any>;
  fileName?: string;
  onExportStart?: () => void;
  onExportComplete?: () => void;
  onExportError?: (error: Error) => void;
  children?: (handleExport: () => Promise<void>) => React.ReactNode;
}

export const LandParcelsExport: React.FC<LandParcelsExportProps> = ({
  data,

  filters,
  fileName,
  onExportStart,
  onExportComplete,
  onExportError,
  children
}) => {
  const handleExport = async () => {
    try {
      if (data.length === 0) {
        alert('No data to export');
        return;
      }

      onExportStart?.();

      const workbook = new ExcelJS.Workbook();
      workbook.creator = 'Land Management System';
      workbook.lastModifiedBy = 'System';
      workbook.created = new Date();
      workbook.modified = new Date();

      // ============== SUMMARY SHEET ==============
      await createSummarySheet(workbook, data, filters);

      // ============== PARCELS DETAIL SHEET ==============
      await createParcelsSheet(workbook, data);

      // ============== OWNERS SHEET ==============
      await createOwnersSheet(workbook, data);

      // Generate filename
      const dateStr = new Date().toISOString().split('T')[0];
      const filterStr = filters.subCityId ? `_${filters.subCityId}` : '';
      const finalFileName = fileName || `land_parcels_report${filterStr}_${dateStr}.xlsx`;

      // Save the file
      const buffer = await workbook.xlsx.writeBuffer();
      const blob = new Blob([buffer], { 
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' 
      });
      saveAs(blob, finalFileName);

      onExportComplete?.();
      console.log(`Exported ${data.length} parcels successfully`);

    } catch (error) {
      console.error('Error exporting land parcels:', error);
      onExportError?.(error as Error);
      alert('Failed to export data. Please try again.');
    }
  };

  const createSummarySheet = async (
    workbook: ExcelJS.Workbook, 
    data: LandParcelReportItem[],
    filters: Record<string, any>
  ) => {
    const summarySheet = workbook.addWorksheet('Summary', {
      properties: { defaultColWidth: 25 }
    });

    // Title
    summarySheet.mergeCells('A1:D1');
    const titleRow = summarySheet.getRow(1);
    titleRow.getCell(1).value = 'Land Parcels Report Summary';
    titleRow.getCell(1).font = { size: 18, bold: true, color: { argb: '2F5597' } };
    titleRow.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };
    titleRow.height = 30;

    // Report Info Section
    summarySheet.addRow([]);
    summarySheet.addRow(['Report Information:']);
    summarySheet.getRow(3).getCell(1).font = { bold: true, size: 12 };

    const infoRows = [
      ['Generated Date:', new Date().toLocaleString()],
      ['Generated By:', 'System'],
      ['Total Parcels:', data.length.toString()],
      ['Sub City:', filters.subCityId || 'All Sub Cities'],
      ['Land Use:', filters.landUse || 'All Land Uses'],
      ['Tenure Type:', filters.tenureType || 'All Tenure Types'],
      ['Status:', filters.status || 'All Statuses'],
      ['Tender:', filters.tender || 'All Tenders'],
      ['Tabia:', filters.tabia || 'All Tabias'],
      ['Ketena:', filters.ketena || 'All Ketenas'],
      ['Block:', filters.block || 'All Blocks'],
      ['Area Range:', filters.minArea || filters.maxArea 
        ? `${filters.minArea || 'Any'} - ${filters.maxArea || 'Any'} m²`
        : 'All Areas'],
      ['Land Grade:', filters.landGrade || 'All Grades']
    ];

    infoRows.forEach((row) => {
      const addedRow = summarySheet.addRow(row);
      addedRow.getCell(1).font = { bold: true };
      addedRow.height = 20;
    });

    // Statistics Section
    summarySheet.addRow([]);
    summarySheet.addRow(['Statistics:']);
    summarySheet.getRow(3 + infoRows.length + 2).getCell(1).font = { bold: true, size: 12 };

    const statusCounts = data.reduce((acc, item) => {
      acc[item.status] = (acc[item.status] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);


    const parcelsWithOwners = data.filter(item => item.owners && item.owners.length > 0).length;
    const totalOwners = data.reduce((sum, item) => sum + (item.owners?.length || 0), 0);

    const statsRows = [
     
      ['Parcels with Owners:', `${parcelsWithOwners} (${((parcelsWithOwners / data.length) * 100).toFixed(1)}%)`],
      ['Total Owners:', totalOwners.toString()],
      ['Average Owners per Parcel:', (totalOwners / data.length).toFixed(2)],
      ...Object.entries(statusCounts).map(([status, count]) => [
        `${status} Parcels:`, 
        `${count} (${((count / data.length) * 100).toFixed(1)}%)`
      ])
    ];

    statsRows.forEach(row => {
      const addedRow = summarySheet.addRow(row);
      addedRow.getCell(1).font = { bold: true };
    });

    // Style the sheet
    summarySheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });
  };

  const createParcelsSheet = async (workbook: ExcelJS.Workbook, data: LandParcelReportItem[]) => {
    const parcelsSheet = workbook.addWorksheet('Land Parcels', {
      properties: { defaultColWidth: 15 },
      views: [{
        state: 'frozen',
        ySplit: 1,
        xSplit: 0
      }]
    });

    // Define columns
    parcelsSheet.columns = [
      { header: 'UPIN', key: 'upin', width: 20 },
      { header: 'File Number', key: 'fileNumber', width: 20 },
      { header: 'Sub City', key: 'subCity', width: 15 },
      { header: 'Tabia', key: 'tabia', width: 15 },
      { header: 'Ketena', key: 'ketena', width: 15 },
      { header: 'Block', key: 'block', width: 15 },
      { header: 'Land Use', key: 'landUse', width: 15 },
      { header: 'Area (m²)', key: 'area', width: 15 },
      { header: 'Land Grade', key: 'landGrade', width: 12 },
      { header: 'Tenure Type', key: 'tenureType', width: 15 },
      { header: 'Tender', key: 'tender', width: 20 },
      { header: 'Status', key: 'status', width: 12 },
      { header: 'Owner Count', key: 'ownerCount', width: 12 },
      { header: 'Boundary East', key: 'boundaryEast', width: 15 },
      { header: 'Boundary North', key: 'boundaryNorth', width: 15 },
      { header: 'Boundary South', key: 'boundarySouth', width: 15 },
      { header: 'Boundary West', key: 'boundaryWest', width: 15 }
    ];

    // Style header
    const headerRow = parcelsSheet.getRow(1);
    headerRow.height = 30;
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, size: 12, color: { argb: 'FFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: '2F5597' }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // Add data rows
    data.forEach((item) => {
      const row = parcelsSheet.addRow({
        upin: item.upin,
        fileNumber: item.file_number,
        subCity: item.sub_city?.name || 'N/A',
        tabia: item.tabia || '-',
        ketena: item.ketena || '-',
        block: item.block || '-',
        landUse: item.land_use || '-',
        area: item.total_area_m2?.toLocaleString() || '-',
        landGrade: item.land_grade || '-',
        tenureType: item.tenure_type || '-',
        tender: item.tender || '-',
        status: item.status,
        ownerCount: item.owners?.length || 0,
        boundaryEast: item.boundary_east || '-',
        boundaryNorth: item.boundary_north || '-',
        boundarySouth: item.boundary_south || '-',
        boundaryWest: item.boundary_west || '-'
      });

      // Style based on status
      const statusCell = row.getCell('status');
      const statusColors: Record<string, { bg: string, text: string }> = {
        ACTIVE: { bg: 'C6EFCE', text: '006100' },
        RETIRED: { bg: 'FFC7CE', text: '9C0006' },
        PENDING: { bg: 'FFEB9C', text: '9C6500' }
      };

      const color = statusColors[item.status];
      if (color) {
        statusCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: color.bg }
        };
        statusCell.font = { color: { argb: color.text } };
      }

      // Highlight parcels without owners
      if (!item.owners?.length) {
        row.getCell('ownerCount').fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFEB9C' }
        };
      }

      // Add borders
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
        cell.alignment = { vertical: 'middle', wrapText: true };
      });

      // Alternate row colors
      if (row.number % 2 === 0) {
        row.eachCell((cell) => {
          if (!cell.fill ) {
            cell.fill = {
              type: 'pattern',
              pattern: 'solid',
              fgColor: { argb: 'F2F2F2' }
            };
          }
        });
      }
    });

    // Add auto-filter
    parcelsSheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: parcelsSheet.columns.length }
    };

    // Add conditional formatting for area
    const areaColumn = parcelsSheet.getColumn('area');
    areaColumn.eachCell((cell, rowNumber) => {
      if (rowNumber > 1 && cell.value && cell.value !== '-') {
        const area = parseFloat(cell.value.toString().replace(/,/g, ''));
        if (area > 1000) {
          cell.font = { bold: true };
        }
      }
    });
  };

  const createOwnersSheet = async (workbook: ExcelJS.Workbook, data: LandParcelReportItem[]) => {
    const ownersSheet = workbook.addWorksheet('Owners Details', {
      properties: { defaultColWidth: 20 },
      views: [{
        state: 'frozen',
        ySplit: 1
      }]
    });

    ownersSheet.columns = [
      { header: 'UPIN', key: 'upin', width: 20 },
      { header: 'File Number', key: 'fileNumber', width: 20 },
      { header: 'Sub City', key: 'subCity', width: 15 },
      { header: 'Tabia', key: 'tabia', width: 15 },
      { header: 'Owner Name', key: 'ownerName', width: 30 },
      { header: 'National ID', key: 'nationalId', width: 20 },
      { header: 'TIN Number', key: 'tinNumber', width: 20 },
      { header: 'Phone Number', key: 'phone', width: 15 },
      { header: 'Acquired Date', key: 'acquiredDate', width: 15 },
     
    ];

    // Style header
    const headerRow = ownersSheet.getRow(1);
    headerRow.height = 30;
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, size: 12 };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'D9E1F2' }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center' };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // Add owner data
    let hasOwners = false;
    data.forEach((item) => {
      if (item.owners && item.owners.length > 0) {
        hasOwners = true;
        item.owners.forEach((ownerRelation) => {
          const row = ownersSheet.addRow({
            upin: item.upin,
            fileNumber: item.file_number,
            subCity: item.sub_city?.name || 'N/A',
            tabia: item.tabia || '-',
            ownerName: ownerRelation.owner.full_name,
            nationalId: ownerRelation.owner.national_id || '-',
            tinNumber: ownerRelation.owner.tin_number || '-',
            phone: ownerRelation.owner.phone_number || '-',
            acquiredDate: new Date(ownerRelation.acquired_at).toLocaleDateString(),
            
           
          });

          row.eachCell((cell) => {
            cell.border = {
              top: { style: 'thin' },
              left: { style: 'thin' },
              bottom: { style: 'thin' },
              right: { style: 'thin' }
            };
            cell.alignment = { vertical: 'middle' };
          });
        });
      }
    });

    if (!hasOwners) {
      ownersSheet.addRow(['No owner data available']);
    } else {
      ownersSheet.autoFilter = {
        from: { row: 1, column: 1 },
        to: { row: 1, column: ownersSheet.columns.length }
      };
    }
  };

  // Render prop pattern
  if (children) {
    return <>{children(handleExport)}</>;
  }

  // Default render as a button
  return (
    <button
      onClick={handleExport}
      disabled={data.length === 0}
      className="px-4 py-2 text-sm font-medium text-white bg-green-600 rounded-lg hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed"
    >
      Export to Excel
    </button>
  );
};