// components/reports/LeaseInstallmentExport.tsx
import React from 'react';
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import type { LeaseInstallmentItem } from '../../types/reports';

interface LeaseInstallmentExportProps {
  data: LeaseInstallmentItem[];
  filters: Record<string, any>;
  subCities?: Array<{ sub_city_id: string; name: string }>;
  fileName?: string;
  onExportStart?: () => void;
  onExportComplete?: () => void;
  onExportError?: (error: Error) => void;
  children?: (handleExport: () => Promise<void>) => React.ReactNode;
}

export const LeaseInstallmentExport: React.FC<LeaseInstallmentExportProps> = ({
  data,
  filters,
  subCities,
  fileName,
  onExportStart,
  onExportComplete,
  onExportError,
  children
}) => {
  const handleExport = async () => {
    try {
      if (data.length === 0) {
        alert('No data to export');
        return;
      }

      onExportStart?.();

      const workbook = new ExcelJS.Workbook();
      workbook.creator = 'Land Management System';
      workbook.lastModifiedBy = 'System';
      workbook.created = new Date();
      workbook.modified = new Date();

      // ============== SUMMARY SHEET ==============
      await createSummarySheet(workbook, data, filters);

      // ============== PARCELS & LEASE DETAILS SHEET ==============
      await createLeaseDetailsSheet(workbook, data);

      // ============== OWNERS SHEET ==============
      await createOwnersSheet(workbook, data);

      // ============== PAYMENT ANALYSIS SHEET ==============
      await createPaymentAnalysisSheet(workbook, data);

      // Generate filename
      const dateStr = new Date().toISOString().split('T')[0];
      const rangeStr = `_${filters.min || 0}_${filters.max || 1000000}`;
      const finalFileName = fileName || `lease_installments${rangeStr}_${dateStr}.xlsx`;

      // Save the file
      const buffer = await workbook.xlsx.writeBuffer();
      const blob = new Blob([buffer], { 
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' 
      });
      saveAs(blob, finalFileName);

      onExportComplete?.();
      console.log(`Exported ${data.length} lease records successfully`);

    } catch (error) {
      console.error('Error exporting lease data:', error);
      onExportError?.(error as Error);
      alert('Failed to export data. Please try again.');
    }
  };

  const createSummarySheet = async (
    workbook: ExcelJS.Workbook, 
    data: LeaseInstallmentItem[],
    filters: Record<string, any>
  ) => {
    const summarySheet = workbook.addWorksheet('Summary', {
      properties: { defaultColWidth: 25 }
    });

    // Title
    summarySheet.mergeCells('A1:D1');
    const titleRow = summarySheet.getRow(1);
    titleRow.getCell(1).value = 'Lease Annual Installment Range Report';
    titleRow.getCell(1).font = { size: 18, bold: true, color: { argb: '2F5597' } };
    titleRow.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };
    titleRow.height = 30;

    // Report Info Section
    summarySheet.addRow([]);
    summarySheet.addRow(['Report Information:']);
    summarySheet.getRow(3).getCell(1).font = { bold: true, size: 12 };

    const totalInstallments = data.reduce((sum, item) => sum + item.lease.annual_installment, 0);
    const minInstallment = data.length > 0 
      ? Math.min(...data.map(item => item.lease.annual_installment)) 
      : 0;
    const maxInstallment = data.length > 0 
      ? Math.max(...data.map(item => item.lease.annual_installment)) 
      : 0;

      const getSubCityName = (subCityId: string): string => {
  if (!subCityId) return 'All Sub Cities';
  const subCity = subCities?.find(sc => sc.sub_city_id === subCityId);
  return subCity?.name || subCityId;
};

    const infoRows = [
      ['Generated Date:', new Date().toLocaleString()],
      ['Generated By:', 'System'],
      ['Total Records:', data.length.toString()],
       ['Sub City:', getSubCityName(filters.subCityId)],
      ['Installment Range:', `${filters.min || 0} ETB - ${filters.max || 1000000} ETB`],
      ['Total Annual Installments:', `${totalInstallments.toLocaleString()} ETB`],
      ['Minimum Installment:', `${minInstallment.toLocaleString()} ETB`],
      ['Maximum Installment:', `${maxInstallment.toLocaleString()} ETB`],
      ['Average Installment:', data.length > 0 
        ? `${(totalInstallments / data.length).toLocaleString()} ETB` 
        : '0 ETB']
    ];

    infoRows.forEach((row) => {
      const addedRow = summarySheet.addRow(row);
      addedRow.getCell(1).font = { bold: true };
      addedRow.height = 20;
    });

    // Status Distribution Section
    summarySheet.addRow([]);
    summarySheet.addRow(['Lease Status Distribution:']);
    summarySheet.getRow(3 + infoRows.length + 2).getCell(1).font = { bold: true, size: 12 };

    const statusCounts = data.reduce((acc, item) => {
      acc[item.lease.status] = (acc[item.lease.status] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    Object.entries(statusCounts).forEach(([status, count]) => {
      const row = summarySheet.addRow([`${status} Leases:`, `${count} (${((count / data.length) * 100).toFixed(1)}%)`]);
      row.getCell(1).font = { bold: true };
    });

    // Style the sheet
    summarySheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });
  };

  const createLeaseDetailsSheet = async (workbook: ExcelJS.Workbook, data: LeaseInstallmentItem[]) => {
    const detailsSheet = workbook.addWorksheet('Lease Details', {
      properties: { defaultColWidth: 15 },
      views: [{
        state: 'frozen',
        ySplit: 1,
        xSplit: 0
      }]
    });

    // Define columns
    detailsSheet.columns = [
      { header: 'UPIN', key: 'upin', width: 20 },
      { header: 'File Number', key: 'fileNumber', width: 20 },
      { header: 'Sub City', key: 'subCity', width: 15 },
      { header: 'Tabia', key: 'tabia', width: 15 },
      { header: 'Ketena', key: 'ketena', width: 15 },
      { header: 'Block', key: 'block', width: 15 },
      { header: 'Land Use', key: 'landUse', width: 15 },
      { header: 'Area (m²)', key: 'area', width: 15 },
      { header: 'Tenure Type', key: 'tenureType', width: 15 },
      { header: 'Annual Installment', key: 'annualInstallment', width: 20 },
      { header: 'Lease Status', key: 'leaseStatus', width: 15 },
      { header: 'Start Date', key: 'startDate', width: 15 },
      { header: 'Expiry Date', key: 'expiryDate', width: 15 },
      { header: 'Owner Count', key: 'ownerCount', width: 12 }
    ];

    // Style header
    const headerRow = detailsSheet.getRow(1);
    headerRow.height = 30;
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, size: 12, color: { argb: 'FFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: '2F5597' }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // Add data rows
    data.forEach((item) => {
      const row = detailsSheet.addRow({
        upin: item.parcel.upin,
        fileNumber: item.parcel.file_number,
        subCity: item.parcel.sub_city_name,
        tabia: item.parcel.tabia || '-',
        ketena: item.parcel.ketena || '-',
        block: item.parcel.block || '-',
        landUse: item.parcel.land_use || '-',
        area: item.parcel.total_area_m2?.toLocaleString() || '-',
        tenureType: item.parcel.tenure_type || '-',
        annualInstallment: `${item.lease.annual_installment.toLocaleString()} ETB`,
        leaseStatus: item.lease.status,
        leaseId: item.lease.lease_id,
        startDate: new Date(item.lease.start_date).toLocaleDateString(),
        expiryDate: item.lease.expiry_date ? new Date(item.lease.expiry_date).toLocaleDateString() : 'N/A',
        ownerCount: item.owners.length
      });

      // Style based on lease status
      const statusCell = row.getCell('leaseStatus');
      const statusColors: Record<string, { bg: string, text: string }> = {
        ACTIVE: { bg: 'C6EFCE', text: '006100' },
        EXPIRED: { bg: 'FFC7CE', text: '9C0006' },
        PENDING: { bg: 'FFEB9C', text: '9C6500' }
      };

      const color = statusColors[item.lease.status];
      if (color) {
        statusCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: color.bg }
        };
        statusCell.font = { color: { argb: color.text } };
      }

      // Highlight high-value installments
      const installmentCell = row.getCell('annualInstallment');
      if (item.lease.annual_installment > 500000) {
        installmentCell.font = { bold: true, color: { argb: '9C0006' } };
      } else if (item.lease.annual_installment > 100000) {
        installmentCell.font = { bold: true, color: { argb: '9C6500' } };
      }

      // Add borders
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
        cell.alignment = { vertical: 'middle', wrapText: true };
      });

      // Alternate row colors
      if (row.number % 2 === 0) {
        row.eachCell((cell) => {
          if (!cell.fill || cell.fill.type === 'none') {
            cell.fill = {
              type: 'pattern',
              pattern: 'solid',
              fgColor: { argb: 'F2F2F2' }
            };
          }
        });
      }
    });

    // Add auto-filter
    detailsSheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: detailsSheet.columns.length }
    };

    // Add conditional formatting for installment amounts
    const installmentColumn = detailsSheet.getColumn('annualInstallment');
    installmentColumn.eachCell((cell, rowNumber) => {
      if (rowNumber > 1 && cell.value) {
        cell.numFmt = '#,##0 "ETB"';
        cell.alignment = { horizontal: 'right' };
      }
    });
  };

  const createOwnersSheet = async (workbook: ExcelJS.Workbook, data: LeaseInstallmentItem[]) => {
    const ownersSheet = workbook.addWorksheet('Owners Details', {
      properties: { defaultColWidth: 20 },
      views: [{
        state: 'frozen',
        ySplit: 1
      }]
    });

    ownersSheet.columns = [
      { header: 'UPIN', key: 'upin', width: 20 },
      { header: 'File Number', key: 'fileNumber', width: 20 },
      { header: 'Sub City', key: 'subCity', width: 15 },
      { header: 'Annual Installment', key: 'annualInstallment', width: 20 },
      { header: 'Lease Status', key: 'leaseStatus', width: 15 },
      { header: 'Owner Name', key: 'ownerName', width: 30 },
      { header: 'National ID', key: 'nationalId', width: 20 },
      { header: 'TIN Number', key: 'tinNumber', width: 20 },
      { header: 'Phone Number', key: 'phone', width: 15 },
      { header: 'Acquired Date', key: 'acquiredDate', width: 15 }
    ];

    // Style header
    const headerRow = ownersSheet.getRow(1);
    headerRow.height = 30;
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, size: 12 };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'D9E1F2' }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center' };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // Add owner data
    let hasOwners = false;
    data.forEach((item) => {
      if (item.owners.length > 0) {
        hasOwners = true;
        item.owners.forEach((owner) => {
          const row = ownersSheet.addRow({
            upin: item.parcel.upin,
            fileNumber: item.parcel.file_number,
            subCity: item.parcel.sub_city_name,
            annualInstallment: `${item.lease.annual_installment.toLocaleString()} ETB`,
            leaseStatus: item.lease.status,
            ownerName: owner.full_name,
            nationalId: owner.national_id || '-',
            tinNumber: owner.tin_number || '-',
            phone: owner.phone_number || '-',
            acquiredDate: new Date(owner.acquired_at).toLocaleDateString()
          });

          row.eachCell((cell) => {
            cell.border = {
              top: { style: 'thin' },
              left: { style: 'thin' },
              bottom: { style: 'thin' },
              right: { style: 'thin' }
            };
            cell.alignment = { vertical: 'middle' };
          });
        });
      }
    });

    if (!hasOwners) {
      ownersSheet.addRow(['No owner data available']);
    } else {
      ownersSheet.autoFilter = {
        from: { row: 1, column: 1 },
        to: { row: 1, column: ownersSheet.columns.length }
      };
    }
  };

  const createPaymentAnalysisSheet = async (workbook: ExcelJS.Workbook, data: LeaseInstallmentItem[]) => {
    const analysisSheet = workbook.addWorksheet('Payment Analysis', {
      properties: { defaultColWidth: 20 }
    });

    // Title
    analysisSheet.mergeCells('A1:C1');
    const titleRow = analysisSheet.getRow(1);
    titleRow.getCell(1).value = 'Payment Analysis Summary';
    titleRow.getCell(1).font = { size: 16, bold: true, color: { argb: '2F5597' } };
    titleRow.getCell(1).alignment = { horizontal: 'center' };
    titleRow.height = 25;

    // Payment Distribution by Range
    analysisSheet.addRow([]);
    analysisSheet.addRow(['Payment Distribution by Range:']);
    analysisSheet.getRow(3).getCell(1).font = { bold: true };

    const ranges = [
      { min: 0, max: 50000, label: '0 - 50,000 ETB' },
      { min: 50001, max: 100000, label: '50,001 - 100,000 ETB' },
      { min: 100001, max: 250000, label: '100,001 - 250,000 ETB' },
      { min: 250001, max: 500000, label: '250,001 - 500,000 ETB' },
      { min: 500001, max: 1000000, label: '500,001 - 1,000,000 ETB' },
      { min: 1000001, max: Infinity, label: '1,000,000+ ETB' }
    ];

    ranges.forEach(range => {
      const count = data.filter(item => 
        item.lease.annual_installment >= range.min && 
        item.lease.annual_installment <= range.max
      ).length;
      
      const total = data
        .filter(item => item.lease.annual_installment >= range.min && item.lease.annual_installment <= range.max)
        .reduce((sum, item) => sum + item.lease.annual_installment, 0);

      if (count > 0) {
        const row = analysisSheet.addRow([range.label, count, `${total.toLocaleString()} ETB`]);
        row.getCell(1).font = { bold: true };
      }
    });

    // Expiring Leases Summary
    analysisSheet.addRow([]);
    analysisSheet.addRow(['Leases Expiring Soon:']);
    analysisSheet.getRow(3 + ranges.length + 3).getCell(1).font = { bold: true };

    const today = new Date();
    const sixMonthsFromNow = new Date();
    sixMonthsFromNow.setMonth(today.getMonth() + 6);

    const expiringLeases = data.filter(item => {
      if (!item.lease.expiry_date) return false;
      const expiryDate = new Date(item.lease.expiry_date);
      return expiryDate <= sixMonthsFromNow && expiryDate > today;
    });

    expiringLeases.sort((a, b) => {
      if (!a.lease.expiry_date || !b.lease.expiry_date) return 0;
      return new Date(a.lease.expiry_date).getTime() - new Date(b.lease.expiry_date).getTime();
    });

    analysisSheet.addRow(['UPIN', 'Expiry Date', 'Annual Installment']);
    expiringLeases.slice(0, 10).forEach(item => {
      if (item.lease.expiry_date) {
        analysisSheet.addRow([
          item.parcel.upin,
          new Date(item.lease.expiry_date).toLocaleDateString(),
          `${item.lease.annual_installment.toLocaleString()} ETB`
        ]);
      }
    });

    // Style the analysis sheet
    analysisSheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });
  };

  // Render prop pattern
  if (children) {
    return <>{children(handleExport)}</>;
  }

  // Default render as a button
  return (
    <button
      onClick={handleExport}
      disabled={data.length === 0}
      className="px-4 py-2 text-sm font-medium text-white bg-green-600 rounded-lg hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed"
    >
      Export to Excel
    </button>
  );
};