// components/reports/OwnersMultipleParcelsExport.tsx
import React from 'react';
import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import type { OwnerMultipleParcelsItem } from '../../types/reports';

interface OwnersMultipleParcelsExportProps {
  data: OwnerMultipleParcelsItem[];
  filters: Record<string, any>;
  subCities?: Array<{ sub_city_id: string; name: string }>;
  fileName?: string;
  onExportStart?: () => void;
  onExportComplete?: () => void;
  onExportError?: (error: Error) => void;
  children?: (handleExport: () => Promise<void>) => React.ReactNode;
}

export const OwnersMultipleParcelsExport: React.FC<OwnersMultipleParcelsExportProps> = ({
  data,
  filters,
  fileName,
  subCities,
  onExportStart,
  onExportComplete,
  onExportError,
  children
}) => {
  const handleExport = async () => {
    try {
      if (data.length === 0) {
        alert('No data to export');
        return;
      }

      onExportStart?.();

      const workbook = new ExcelJS.Workbook();
      workbook.creator = 'Land Management System';
      workbook.lastModifiedBy = 'System';
      workbook.created = new Date();
      workbook.modified = new Date();

      // ============== SUMMARY SHEET ==============
      await createSummarySheet(workbook, data, filters);

      // ============== OWNERS SUMMARY SHEET ==============
      await createOwnersSummarySheet(workbook, data);

      // ============== DETAILED PARCELS SHEET ==============
      await createDetailedParcelsSheet(workbook, data);

      // ============== STATISTICS SHEET ==============
      await createStatisticsSheet(workbook, data);

      // Generate filename
      const dateStr = new Date().toISOString().split('T')[0];
      const minParcelsStr = filters.minParcels ? `_min${filters.minParcels}` : '';
      const finalFileName = fileName || `owners_multiple_parcels${minParcelsStr}_${dateStr}.xlsx`;

      // Save the file
      const buffer = await workbook.xlsx.writeBuffer();
      const blob = new Blob([buffer], { 
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' 
      });
      saveAs(blob, finalFileName);

      onExportComplete?.();
      console.log(`Exported ${data.length} owners with multiple parcels successfully`);

    } catch (error) {
      console.error('Error exporting owners data:', error);
      onExportError?.(error as Error);
      alert('Failed to export data. Please try again.');
    }
  };

  const createSummarySheet = async (
    workbook: ExcelJS.Workbook, 
    data: OwnerMultipleParcelsItem[],
    filters: Record<string, any>
  ) => {
    const summarySheet = workbook.addWorksheet('Summary', {
      properties: { defaultColWidth: 25 }
    });

    // Title
    summarySheet.mergeCells('A1:D1');
    const titleRow = summarySheet.getRow(1);
    titleRow.getCell(1).value = 'Owners with Multiple Parcels Report';
    titleRow.getCell(1).font = { size: 18, bold: true, color: { argb: '2F5597' } };
    titleRow.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };
    titleRow.height = 30;

    // Report Info Section
    summarySheet.addRow([]);
    summarySheet.addRow(['Report Information:']);
    summarySheet.getRow(3).getCell(1).font = { bold: true, size: 12 };

    const totalParcels = data.reduce((sum, owner) => sum + owner.parcel_count, 0);
    const maxParcels = data.length > 0 
      ? Math.max(...data.map(owner => owner.parcel_count)) 
      : 0;
    const ownersWithContact = data.filter(owner => owner.phone_number).length;
    const ownersWithNationalId = data.filter(owner => owner.national_id).length;
const getSubCityName = (subCityId: string): string => {
  if (!subCityId) return 'All Sub Cities';
  console.log("subcities",subCities)
  console.log()
  const subCity = subCities?.find(sc => sc.sub_city_id === subCityId);
  return subCity?.name || subCityId;
};
    const infoRows = [
      ['Generated Date:', new Date().toLocaleString()],
      ['Generated By:', 'System'],
      ['Total Owners with Multiple Parcels:', data.length.toString()],
      ['Minimum Parcels Filter:', filters.minParcels?.toString() || '2'],
       ['Sub City:',getSubCityName(filters.subCityId) ],
      ['Total Parcels Owned:', totalParcels.toString()],
      ['Average Parcels per Owner:', (totalParcels / data.length).toFixed(2)],
      ['Maximum Parcels Owned by Single Owner:', maxParcels.toString()],
      ['Owners with Phone Numbers:', `${ownersWithContact} (${((ownersWithContact / data.length) * 100).toFixed(1)}%)`],
      ['Owners with National ID:', `${ownersWithNationalId} (${((ownersWithNationalId / data.length) * 100).toFixed(1)}%)`]
    ];

    infoRows.forEach((row) => {
      const addedRow = summarySheet.addRow(row);
      addedRow.getCell(1).font = { bold: true };
      addedRow.height = 20;
    });

    // Parcel Distribution Section
    summarySheet.addRow([]);
    summarySheet.addRow(['Parcel Distribution:']);
    summarySheet.getRow(3 + infoRows.length + 2).getCell(1).font = { bold: true, size: 12 };

    const distribution: Record<number, number> = {};
    data.forEach(owner => {
      distribution[owner.parcel_count] = (distribution[owner.parcel_count] || 0) + 1;
    });

    Object.entries(distribution)
      .sort(([a], [b]) => Number(a) - Number(b))
      .forEach(([parcelCount, ownerCount]) => {
        const row = summarySheet.addRow([
          `Owners with ${parcelCount} parcels:`, 
          `${ownerCount} (${((ownerCount / data.length) * 100).toFixed(1)}%)`
        ]);
        row.getCell(1).font = { bold: true };
      });

    // Style the sheet
    summarySheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
      });
    });
  };

  const createOwnersSummarySheet = async (workbook: ExcelJS.Workbook, data: OwnerMultipleParcelsItem[]) => {
    const ownersSheet = workbook.addWorksheet('Owners Summary', {
      properties: { defaultColWidth: 18 },
      views: [{
        state: 'frozen',
        ySplit: 1,
        xSplit: 0
      }]
    });

    // Define columns
    ownersSheet.columns = [
      { header: 'Owner Name', key: 'ownerName', width: 30 },
      { header: 'National ID', key: 'nationalId', width: 20 },
      { header: 'TIN Number', key: 'tinNumber', width: 20 },
      { header: 'Phone Number', key: 'phone', width: 18 },
      { header: 'Email', key: 'email', width: 25 },
      { header: 'Sub City', key: 'subCity', width: 18 },
      { header: 'Total Parcels', key: 'totalParcels', width: 15 },
      { header: 'Total Area (m²)', key: 'totalArea', width: 18 },
      { header: 'Active Parcels', key: 'activeParcels', width: 15 },
      { header: 'Inactive Parcels', key: 'inactiveParcels', width: 15 }
    ];

    // Style header
    const headerRow = ownersSheet.getRow(1);
    headerRow.height = 30;
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, size: 12, color: { argb: 'FFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: '2F5597' }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // Add data rows
    data.forEach((owner) => {
      const totalArea = owner.parcels.reduce((sum, p) => sum + (p.total_area_m2 || 0), 0);
      const activeParcels = owner.parcels.filter(p => p.status === 'ACTIVE').length;
      const inactiveParcels = owner.parcels.filter(p => p.status !== 'ACTIVE').length;

      const row = ownersSheet.addRow({
        ownerName: owner.full_name,
        nationalId: owner.national_id || '-',
        tinNumber: owner.tin_number || '-',
        phone: owner.phone_number || '-',
        subCity: owner.sub_city_name || 'N/A',
        totalParcels: owner.parcel_count,
        totalArea: totalArea.toLocaleString(),
        activeParcels: activeParcels,
        inactiveParcels: inactiveParcels
      });

      // Style based on parcel count
      const parcelCountCell = row.getCell('totalParcels');
      if (owner.parcel_count >= 5) {
        parcelCountCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'C6EFCE' }
        };
        parcelCountCell.font = { bold: true, color: { argb: '006100' } };
      } else if (owner.parcel_count >= 3) {
        parcelCountCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFEB9C' }
        };
        parcelCountCell.font = { bold: true, color: { argb: '9C6500' } };
      }

      // Highlight owners without contact info
      if (!owner.phone_number) {
        row.getCell('phone').fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFC7CE' }
        };
      }

      // Add borders
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
        cell.alignment = { vertical: 'middle', wrapText: true };
      });

      // Alternate row colors
      if (row.number % 2 === 0) {
        row.eachCell((cell) => {
          if (!cell.fill ) {
            cell.fill = {
              type: 'pattern',
              pattern: 'solid',
              fgColor: { argb: 'F2F2F2' }
            };
          }
        });
      }
    });

    // Add auto-filter
    ownersSheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: ownersSheet.columns.length }
    };
  };

  const createDetailedParcelsSheet = async (workbook: ExcelJS.Workbook, data: OwnerMultipleParcelsItem[]) => {
    const parcelsSheet = workbook.addWorksheet('All Parcels', {
      properties: { defaultColWidth: 15 },
      views: [{
        state: 'frozen',
        ySplit: 1,
        xSplit: 0
      }]
    });

    // Define columns
    parcelsSheet.columns = [
      { header: 'Owner Name', key: 'ownerName', width: 25 },
      { header: 'UPIN', key: 'upin', width: 20 },
      { header: 'File Number', key: 'fileNumber', width: 20 },
      { header: 'Sub City', key: 'subCity', width: 15 },
      { header: 'Tabia', key: 'tabia', width: 15 },
      { header: 'Ketena', key: 'ketena', width: 15 },
      { header: 'Block', key: 'block', width: 15 },
      { header: 'Area (m²)', key: 'area', width: 15 },
      { header: 'Land Use', key: 'landUse', width: 15 },
      { header: 'Parcel Status', key: 'status', width: 15 }
    ];

    // Style header
    const headerRow = parcelsSheet.getRow(1);
    headerRow.height = 30;
    headerRow.eachCell((cell) => {
      cell.font = { bold: true, size: 12, color: { argb: 'FFFFFF' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: '2F5597' }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
      cell.border = {
        top: { style: 'thin' },
        left: { style: 'thin' },
        bottom: { style: 'thin' },
        right: { style: 'thin' }
      };
    });

    // Add data rows
    data.forEach((owner) => {
      owner.parcels.forEach((parcel) => {
        const row = parcelsSheet.addRow({
          ownerName: owner.full_name,
          upin: parcel.upin,
          fileNumber: parcel.file_number,
          subCity: owner.sub_city_name || 'N/A',
          tabia: parcel.tabia || '-',
          ketena: parcel.ketena || '-',
          block: parcel.block || '-',
          area: parcel.total_area_m2?.toLocaleString() || '-',
          landUse: parcel.land_use || '-',
          status: parcel.status
        });

        // Style based on parcel status
        const statusCell = row.getCell('status');
        const statusColors: Record<string, { bg: string, text: string }> = {
          ACTIVE: { bg: 'C6EFCE', text: '006100' },
          RETIRED: { bg: 'FFC7CE', text: '9C0006' },
          PENDING: { bg: 'FFEB9C', text: '9C6500' }
        };

        const color = statusColors[parcel.status];
        if (color) {
          statusCell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: color.bg }
          };
          statusCell.font = { color: { argb: color.text } };
        }

        // Add borders
        row.eachCell((cell) => {
          cell.border = {
            top: { style: 'thin' },
            left: { style: 'thin' },
            bottom: { style: 'thin' },
            right: { style: 'thin' }
          };
          cell.alignment = { vertical: 'middle', wrapText: true };
        });
      });
    });

    // Add auto-filter
    parcelsSheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: parcelsSheet.columns.length }
    };
  };

  const createStatisticsSheet = async (workbook: ExcelJS.Workbook, data: OwnerMultipleParcelsItem[]) => {
    const statsSheet = workbook.addWorksheet('Statistics', {
      properties: { defaultColWidth: 20 }
    });

    // Title
    statsSheet.mergeCells('A1:C1');
    const titleRow = statsSheet.getRow(1);
    titleRow.getCell(1).value = 'Advanced Statistics';
    titleRow.getCell(1).font = { size: 16, bold: true, color: { argb: '2F5597' } };
    titleRow.getCell(1).alignment = { horizontal: 'center' };
    titleRow.height = 25;

    // Top Owners by Parcel Count
    statsSheet.addRow([]);
    statsSheet.addRow(['Top 10 Owners by Parcel Count:']);
    statsSheet.getRow(3).getCell(1).font = { bold: true };

    const topOwners = [...data]
      .sort((a, b) => b.parcel_count - a.parcel_count)
      .slice(0, 10);

    statsSheet.addRow(['Rank', 'Owner Name', 'Parcel Count', 'Total Area (m²)']);
    topOwners.forEach((owner, index) => {
      const totalArea = owner.parcels.reduce((sum, p) => sum + (p.total_area_m2 || 0), 0);
      statsSheet.addRow([
        (index + 1).toString(),
        owner.full_name,
        owner.parcel_count,
        totalArea.toLocaleString()
      ]);
    });

    // Sub City Distribution
    statsSheet.addRow([]);
    statsSheet.addRow(['Distribution by Sub City:']);
    statsSheet.getRow(3 + topOwners.length + 4).getCell(1).font = { bold: true };

    const subCityMap = new Map<string, { owners: number, parcels: number, area: number }>();
    
    data.forEach(owner => {
      const subCity = owner.sub_city_name || 'Unknown';
      const current = subCityMap.get(subCity) || { owners: 0, parcels: 0, area: 0 };
      
      current.owners += 1;
      current.parcels += owner.parcel_count;
      current.area += owner.parcels.reduce((sum, p) => sum + (p.total_area_m2 || 0), 0);
      
      subCityMap.set(subCity, current);
    });

    statsSheet.addRow(['Sub City', 'Owners', 'Parcels', 'Total Area (m²)']);
    subCityMap.forEach((value, subCity) => {
      statsSheet.addRow([
        subCity,
        value.owners,
        value.parcels,
        value.area.toLocaleString()
      ]);
    });

    // Parcel Status Summary
    statsSheet.addRow([]);
    statsSheet.addRow(['Parcel Status Summary:']);
    statsSheet.getRow(3 + topOwners.length + subCityMap.size + 8).getCell(1).font = { bold: true };

    const statusCounts = { ACTIVE: 0, RETIRED: 0, PENDING: 0, OTHER: 0 };
    data.forEach(owner => {
      owner.parcels.forEach(parcel => {
        if (parcel.status in statusCounts) {
          statusCounts[parcel.status as keyof typeof statusCounts]++;
        } else {
          statusCounts.OTHER++;
        }
      });
    });

    Object.entries(statusCounts).forEach(([status, count]) => {
      statsSheet.addRow([status, count]);
    });

    // Style the statistics sheet
    statsSheet.eachRow((row, rowNumber) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin' },
          left: { style: 'thin' },
          bottom: { style: 'thin' },
          right: { style: 'thin' }
        };
        
        // Style headers
        if (rowNumber === 3 || rowNumber === 3 + topOwners.length + 4 || rowNumber === 3 + topOwners.length + subCityMap.size + 8) {
          cell.font = { bold: true };
          cell.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'D9E1F2' }
          };
        }
      });
    });
  };

  // Render prop pattern
  if (children) {
    return <>{children(handleExport)}</>;
  }

  // Default render as a button
  return (
    <button
      onClick={handleExport}
      disabled={data.length === 0}
      className="px-4 py-2 text-sm font-medium text-white bg-green-600 rounded-lg hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed"
    >
      Export to Excel
    </button>
  );
};